version: '3.7'
services:

  server:
    user: root
    build:
      context: .
    environment:
      - SALMON_DEBUG  # pass through to backend
      - SALMON_NO_AUTH
    ports:
      - "8421:8421"
      - "8400:8400"
      - "8787:8787"
    expose:
      - 8421
      - 8400
      - 8787
    volumes:
      - ".:/salmon:rw"

  redis:
    user: root
    image: redislabs/rejson
    sysctls:  # https://github.com/docker-library/redis/issues/191
      - net.core.somaxconn=65535
      - net.core.somaxconn=511
    expose:
      - 6379
    volumes:
      - "./out:/data:rw"
    entrypoint: /bin/sh -c "chown -v redis:redis /data && chmod -v 777 /data"
    # also https://github.com/boot2docker/boot2docker/issues/1083#issuecomment-151380687

  redismonitor:
    user: root
    build: docker/redismonitor
    ports:
      - "7381:7389"
    volumes:
      - "./out:/logs:rw"
    logging:
      driver: none

  prom:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./docker/prom:/etc/prometheus
        #  granfna:
        #    image: grafana/grafana
        #    ports:
        #      - "3000:3000"

# To get bash on one of these machines:
# docker exec -it <containerIdOrName> bash
