version: '3.7'
services:

  frontend:
    build: frontend
    environment:
      - SALMON_NO_AUTH  # pass through to backend
    ports:
      - "8000:8000"

  redis:
    image: redislabs/rejson
    ports:
      - '6379:6379'
