version: '3.7'
services:

  server:
    user: root
    build:
      context: .
    environment:
      - SALMON_DEBUG  # pass through to backend
      - LOG_LEVEL
    ports:
      - "8421:8421"
      - "8400:8400"
      - "8787:8787"
    depends_on: [redis]
    expose:
      - 8421
      - 8400
      - 8787
    volumes:
      - ".:/salmon:rw"

  redis:
    user: root
    image: redislabs/rejson
    sysctls:  # https://github.com/docker-library/redis/issues/191
      - net.core.somaxconn=65535
      - net.core.somaxconn=511
    expose:
      - 6379
    volumes:
      - "./salmon/_out:/data:rw"
    command: /bin/sh -c "chmod -v 777 /data && redis-server --loadmodule /usr/lib/redis/modules/rejson.so"

  prom:
    image: prom/prometheus
    depends_on: [redis]
    expose:
      - 9090
    volumes:
      - ./docker/prom:/etc/prometheus

  # redismonitor:
  #   user: root
  #   build: docker/redismonitor
  #   ports:
  #     - "7381:7389"
  #   volumes:
  #     - "./out:/logs:rw"
  #   logging:
  #     driver: none

# redis-server command from https://hub.docker.com/r/redislabs/rejson/dockerfile
#
# https://github.com/docker/compose/issues/3270
# also https://github.com/boot2docker/boot2docker/issues/1083#issuecomment-151380687

# To get bash on one of these machines:
# docker exec -it <containerIdOrName> bash
