version: '3.7'
services:

  server:
    build: .
    environment:
      - SALMON_DEBUG  # pass through to backend
      - SALMON_NO_AUTH
    ports:
      - "8421:8421"
    volumes:
      - type: bind
        source: .
        target: /usr/src/salmon

  redis:
    image: redislabs/rejson
    sysctls:  # https://github.com/docker-library/redis/issues/191
      - net.core.somaxconn=65535
      - net.core.somaxconn=511
    volumes:
      - type: bind
        source: ./salmon/frontend
        target: /data
    # also https://github.com/boot2docker/boot2docker/issues/1083#issuecomment-151380687

# To get bash on one of these machines:
# docker exec -it <containerIdOrName> bash
