version: '3.7'
services:

  server:
    build: .
    environment:
      - SALMON_DEBUG  # pass through to backend
      - SALMON_NO_AUTH
    ports:
      - "8421:8421"
      - "8400:8400"
    expose:
      - 8421
      - 8400
    volumes:
      - type: bind
        source: .
        target: /usr/src/salmon

  redis:
    image: redislabs/rejson
    sysctls:  # https://github.com/docker-library/redis/issues/191
      - net.core.somaxconn=65535
      - net.core.somaxconn=511
    expose:
      - 6379
    volumes:
      - type: bind
        source: ./salmon/out
        target: /data
    # also https://github.com/boot2docker/boot2docker/issues/1083#issuecomment-151380687

  dask-scheduler:
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    build:
      context: .
      dockerfile: DockerfileDask

  dask-worker:
    image: daskdev/dask
    hostname: dask-worker
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
    build:
      context: .
      dockerfile: DockerfileDask

  redismonitor:
    build: docker/redismonitor
    ports:
      - "7381:7389"
    volumes:
      - type: bind
        source: ./salmon/out
        target: /logs
    logging:
      driver: none

  prom:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./docker/prom:/etc/prometheus
        #  granfna:
        #    image: grafana/grafana
        #    ports:
        #      - "3000:3000"

# To get bash on one of these machines:
# docker exec -it <containerIdOrName> bash
