version: '3.7'
services:

  frontend:
    build: frontend
    environment:
      - SALMON_NO_AUTH  # pass through to backend
    ports:
      - "8421:8421"

  redis:
    image: redislabs/rejson

# To get bash on one of these machines:
# docker exec -it <containerIdOrName> bash

