html:
  arrow_keys: true
  css: ''
  debrief: <b>Thanks!</b> Please use the participant ID below.
  instructions: Please select the <i>comparison</i> item that is most similar to the
    <i>target</i> item.
  max_queries: 50
  skip_button: false
  title: "Similarity judgements"
  query_params: ['puid']
  element_top: ""
  element_middle: ""
  element_bottom: ""
  element_standalone: ""
  js: ""
samplers:
  random:
    class: Random
sampling:
  common:
    d: 2
  probs:
    random: 100
  samplers_per_user: 0
  details: {}
targets: ["actually", "required", "with", "zip", "or", "yaml"]
