name: Offline tests (install w/ pip)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Debug info
      run: |
          echo "Running pwd..."
          pwd
          echo "CONDA?"
          echo $CONDA
          echo "GITHUB_PATH?"
          echo $GITHUB_PATH
          echo "\nRunning echo $USER..."
          echo $USER
          echo "\nRunning chown..."
          sudo chown -R -H -L $USER:$USER  /home/runner/work/salmon/
          chown -R -H -L $USER:$USER /home/runner/work/salmon/
          echo "\nRunning chmod..."
          sudo chmod -R 777 /home/runner/work/salmon/
          echo "\nRunning `ls`..."
          ls
    - name: Prepare for docker build...
      run: |
          chmod +x launch.sh
          # chown -R -H -L $USER:$USER .
          sudo chown -R -H -L $USER:$USER .
          sudo chown -R -H -L $USER:$USER salmon docs tests
    - name: Install Salmon
      run:
        pip install .
        pip install pytest
    - name: change directories
      run: cd /
    - name: Debug info (salmon.__file__)
      run: |
          echo "Running python -c 'import salmon; print(salmon.__file__)'..."
          python -c "import salmon; print(salmon.__file__)"
    - name: Run offline tests
      run: sudo /usr/share/miniconda/bin/pytest /home/runner/work/salmon/salmon/tests/test_offline.py
    - name: Run tests in salmon/salmon/
      run: sudo /usr/share/miniconda/bin/pytest /home/runner/work/salmon/salmon/salmon
