name: Test Salmon server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file salmon.yml --name base
    - name: Install Salmon
      run: pip install -e .
    - name: Build Salmon server w/ Docker
      run: |
          chmod +x launch.sh
          docker-compose up
    - name: Run tests
      run: pytest
